spring:
  mvc:
    view.prefix: /WEB-INF/jsp/
    view.suffix: .jsp

  data:
    jpa.repositories.bootstrap-mode: deferred

  datasource:
    url: jdbc:postgresql://localhost:5432/pdftodolist
    username: art
    password: art

  jpa:
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect

    hibernate:
      ddl-auto: create
      #ddl-auto = update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

