spring:
    mvc:
        view.prefix: /WEB-INF/jsp/
        view.suffix: .jsp

    datasource:
        url: jdbc:mysql://localhost:3306/pdftodolist?autoReconnect=true&useSSL=false
        username: work
        password: XXX
        # Keep the connection alive if idle for a long time (needed in production)
        testWhileIdle: true
        validationQuery: SELECT 1

    jpa:
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

        hibernate:
            ddl-auto: create
            #ddl-auto = update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

